### ISSUE TITLE
Data validation or schema validation on table

### ISSUE THREAD

**Issue by GaikwadPratik** [rethinkdb/rethinkdb-ts#37]
This is more of a question than bug.

@ronzeidman,

Is there anyway I can utilize JSON schema validators such as [AJV](https://github.com/epoberezkin/ajv) on the write operations at the least through this library?

**Comment by ronzeidman** [comment]
since `update` can be a function it's impossible to validate it unless we create a parser that will take a json schema and convert it to a function that we can save as "write hooks", this can take some effort but is possible, but will only work on rethinkDB versions that support write hooks (>2.3.6) 
creating a client-side schema validator is only partially possible for inserts (only ones that are not a part of a bigger query) and for updates (only ones that are not part of a bigger query or functions, or partial updates)

**Comment by atassis** [comment]
Since this is a database driver, the minimal and needed functionality for this repo is to provide all queries and database standard functionality (like `setWriteHook`). Making schema validation lies beyond current scope of features. 
If you have any questions- you can create a new issue. Closing this one
